[package]
name = "commons-logos-testnet-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
commons-logos-testnet-primitives = { path = "../primitives", features = ["host"] }
lee_core = { workspace = true, features = ["host"] }
risc0-zkvm.workspace = true
risc0-binfmt.workspace = true
risc0-zkos-v1compat.workspace = true
serde.workspace = true
